package com.mcjty.rftools.dimension.world.types;

public enum EffectType {
    EFFECT_NONE,
    EFFECT_NOGRAVITY,
    EFFECT_POISON,
    EFFECT_MOVESLOWDOWN,
    EFFECT_MOVESPEED,
    EFFECT_DIGSLOWDOWN,
    EFFECT_DIGSPEED,
    EFFECT_DAMAGEBOOST,
    EFFECT_HEAL,
    EFFECT_HARM,
    EFFECT_JUMP,
    EFFECT_REGENERATION,
    EFFECT_CONFUSION,
    EFFECT_RESISTANCE,
    EFFECT_FIRERESISTANCE,
    EFFECT_WATERBREATHING,
    EFFECT_INVISIBILITY,
    EFFECT_BLINDNESS,
    EFFECT_NIGHTVISION,
    EFFECT_HUNGER,
    EFFECT_WEAKNESS,
    EFFECT_WITHER,
    EFFECT_HEALTHBOOST,
    EFFECT_ABSORPTION,
    EFFECT_HEALTH
}
