package com.mcjty.rftools;

public enum PlayerBuff {
    BUFF_FEATHERFALLING,
    BUFF_HASTE,
    BUFF_HASTEPLUS,
    BUFF_REGENERATION,
    BUFF_REGENERATIONPLUS,
    BUFF_SATURATION,
    BUFF_SATURATIONPLUS,
    BUFF_SPEED,
    BUFF_SPEEDPLUS
}
